#!/bin/sh

install_zsh () { #{{{
    install zsh/zshrc .zshrc
    install zsh/zshenv .zshenv
} #}}}

install_tcsh () { #{{{
    install .tcshrc
} #}}}

install_bash () { #{{{
    install bash/bashrc .bashrc
    install bash/bash_profile .bash_profile
} #}}}

install_screen () { #{{{
    install .screenrc
} #}}}

# install_tmux () { #{{{
#     install .tmux.conf
# } #}}}

install_git () { #{{{
    install .gitconfig
} #}}}

install_vim () { #{{{
    install .vim
} #}}}

install_xonsh () { # {{{
    install .xonshrc
} # }}}

cd $(dirname $0)
source_dir=$(pwd -P)
cd - >/dev/null

targets=$(cat $source_dir/setup | grep '^install_.*()' | sed 's/install_\(.*\)().*$/\1/')

if [ $# -eq 0 ]; then
    echo 'Available targets:'
    echo '    all'
    echo "$targets" | sed 's/^/    /'
    exit 64 # man errno
fi

. $source_dir/.setup-tools

BACKUP_TOP_FOLDER=".old_rcfiles"
BACKUP_DIR_NAME="`date +%Y%m%d_%H%M%S`"
BACKUP_FILE_PATH="$HOME/$BACKUP_TOP_FOLDER/$BACKUP_DIR_NAME"

while [ $# -gt 0 ]; do
    if [ "$1" = 'all' ] || (echo "$targets" | grep "$1" >/dev/null 2>&1); then
        message_install_start $1
        install_${1}
        message_install_complete $1
        echo ''
    else
        message_unknown_target $1
    fi

    shift
done

if [ -d $BACKUP_FILE_PATH ]; then
    printf "Old files is in $BACKUP_FILE_PATH\n"
fi
