" ============================================================================ "
" Vundle initialization
" ============================================================================ "

" no vi-compatible
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

" Plugins
Bundle 'gmarik/Vundle.vim'
Bundle 'The-NERD-tree'
"Bundle 'Rykka/riv.vim'
Bundle 'tomtom/tcomment_vim'
Bundle 'pi314/BoshiamyIM'
Bundle 'pi314/AsciiArt'
Bundle 'tpope/vim-surround'
Bundle 'pi314/pi314.rst.vim'

call vundle#end()           " required
filetype plugin on          " required
" ============================================================================ "
" Vundle ok "
" ============================================================================ "

" Encoding settings
set encoding=utf-8
set langmenu=zh_TW.UTF-8
language message zh_TW.UTF-8
set fileformat=unix
set ambiwidth=double

" Show mode on bottom-left
set showmode

" Show command on bottom-right
set showcmd

" Color settings
syntax on
set hlsearch
set bg=dark

" Tab charactor related settings
set expandtab       " changes user pressed TAB to spaces
set smarttab
set nosmartindent
set autoindent
set tabstop=4       " changes the width of the TAB character
set shiftwidth=4    " >>, <<, == width and automatic indent width
set listchars=tab:>-
set list

set wrap

" Ignore case on searching
set ignorecase

" Show the coordinate of cursor
set ru

" Enable backspace
set bs=2

" Show line numbers
set nu

" Status line
set laststatus=2
set wildmenu

set scrolloff=5

" tell vim don't create {filename}~
set nobackup
set nowritebackup
" tell vim don't create .{filename}.un~
set noundofile

" set fold method as marker
set fdm=marker

" Funny Setting
set norightleft

" Disable X11 clipboard, it help vim not hanging on start
set clipboard=exclude:.*

" Tabline setting in .vim/plugin/tabline.vim
hi TabLine     ctermfg=black ctermbg=grey     " not active tab page label
hi TabLineSel  ctermfg=grey  ctermbg=black    " active tab page label
hi TabLineFill ctermfg=grey  ctermbg=white    " fill the other place
hi VIMlogo     ctermfg=white ctermbg=blue

" ======== "
" Hot-keys "
" ======== "

" move moving between long wrapped lines
" must use nnoremap = no recursive map
nnoremap k gk
nnoremap j gj

nnoremap th :tabp<CR>
nnoremap tl :tabn<CR>
nnoremap tt :tabe<SPACE>
nnoremap tp :tabm -1<CR>
nnoremap tn :tabm +1<CR>

" toggle the nerd tree
nnoremap <C-n> :NERDTreeToggle<CR>

" Insert a new line in normal mode, I just lazy
nnoremap <CR> o<ESC>0D

" map these by hand
inoremap <C-h> <BS>
nnoremap <C-h> <BS>

" hot key for macro register ``q`` / ``z``
" Do register ``q`` / ``z``
nnoremap dq @q
nnoremap dz @z

" mappings for iterm2
cnoremap <ESC>[A <UP>
cnoremap <ESC>[D <LEFT>
cnoremap <ESC>[C <RIGHT>
cnoremap <ESC>[B <DOWN>
inoremap <ESC>[A <UP>
inoremap <ESC>[D <LEFT>
inoremap <ESC>[C <RIGHT>
inoremap <ESC>[B <DOWN>
nnoremap <ESC>[A <UP>
nnoremap <ESC>[D <LEFT>
nnoremap <ESC>[C <RIGHT>
nnoremap <ESC>[B <DOWN>

nnoremap <leader><C-l> :syntax sync fromstart<CR>

set pastetoggle=<leader>p

" change completion menu color
highlight Pmenu    ctermfg=7 ctermbg=4 gui=bold
highlight PmenuSel ctermfg=0 ctermbg=6 gui=bold

" BoshiamyIM
set statusline=%<%{BoshiamyIM#Status()}%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
inoremap <expr> ,, BoshiamyIM#ToggleIM()
inoremap <space> <C-R>=BoshiamyIM#SendKey()<CR>
nnoremap <expr> <ESC><ESC> BoshiamyIM#LeaveIM()
