setlocal ambiwidth=single
setlocal commentstring=--%s

imap <buffer> \'{z} ź
imap <buffer> \.{B} Ḃ
imap <buffer> \.{C} Ċ
imap <buffer> \.{D} Ḋ
imap <buffer> \.{F} Ḟ
imap <buffer> \! ¡
imap <buffer> \.\=A Ǡ
imap <buffer> \" ̈
imap <buffer> \.\=O Ȱ
imap <buffer> \# ♯
imap <buffer> \.\=a ǡ
imap <buffer> \& ⅋
imap <buffer> \.\=o ȱ
imap <buffer> \* ⋆
imap <buffer> \.{A} Ȧ
imap <buffer> \0 ∅
imap <buffer> \.{E} Ė
imap <buffer> \< ⟨
imap <buffer> \.{G} Ġ
imap <buffer> \= ̄
imap <buffer> \.{H} Ḣ
imap <buffer> \> ⟩
imap <buffer> \.{I} İ
imap <buffer> \? ¿
imap <buffer> \.{M} Ṁ
imap <buffer> \C ∁
imap <buffer> \.{N} Ṅ
imap <buffer> \H ̋
imap <buffer> \.{O} Ȯ
imap <buffer> \I ⋂
imap <buffer> \.{P} Ṗ
imap <buffer> \L Ł
imap <buffer> \.{R} Ṙ
imap <buffer> \O Ø
imap <buffer> \.{S} Ṡ
imap <buffer> \P ¶
imap <buffer> \.{T} Ṫ
imap <buffer> \S §
imap <buffer> \.{W} Ẇ
imap <buffer> \^ ̂
imap <buffer> \.{X} Ẋ
imap <buffer> \k ̨
imap <buffer> \.{Y} Ẏ
imap <buffer> \v ̌
imap <buffer> \.{Z} Ż
imap <buffer> \x ×
imap <buffer> \.{a} ȧ
imap <buffer> \<bar> ∣
imap <buffer> \.{b} ḃ
imap <buffer> \!! ‼
imap <buffer> \.{c} ċ
imap <buffer> \!? ⁉
imap <buffer> \.{d} ḋ
imap <buffer> \"' “
imap <buffer> \.{e} ė
imap <buffer> \"< «
imap <buffer> \.{f} ḟ
imap <buffer> \"> »
imap <buffer> \.{g} ġ
imap <buffer> \"A Ä
imap <buffer> \.{h} ḣ
imap <buffer> \"E Ë
imap <buffer> \.{m} ṁ
imap <buffer> \"H Ḧ
imap <buffer> \.{n} ṅ
imap <buffer> \"I Ï
imap <buffer> \.{o} ȯ
imap <buffer> \"O Ö
imap <buffer> \.{p} ṗ
imap <buffer> \"U Ü
imap <buffer> \.{r} ṙ
imap <buffer> \"W Ẅ
imap <buffer> \.{s} ṡ
imap <buffer> \"X Ẍ
imap <buffer> \.{t} ṫ
imap <buffer> \"Y Ÿ
imap <buffer> \.{w} ẇ
imap <buffer> \"` „
imap <buffer> \.{x} ẋ
imap <buffer> \"a ä
imap <buffer> \.{y} ẏ
imap <buffer> \"e ë
imap <buffer> \.{z} ż
imap <buffer> \"h ḧ
imap <buffer> \<--> ⟷
imap <buffer> \"i ï
imap <buffer> \<->n ↮
imap <buffer> \"o ö
imap <buffer> \<=>n ⇎
imap <buffer> \"t ẗ
imap <buffer> \<~nn ≴
imap <buffer> \"u ü
imap <buffer> \=\"U Ṻ
imap <buffer> \"w ẅ
imap <buffer> \=\"u ṻ
imap <buffer> \"x ẍ
imap <buffer> \=\'E Ḗ
imap <buffer> \"y ÿ
imap <buffer> \=\'O Ṓ
imap <buffer> \'A Á
imap <buffer> \=\'e ḗ
imap <buffer> \'C Ć
imap <buffer> \=\'o ṓ
imap <buffer> \'E É
imap <buffer> \=\AE Ǣ
imap <buffer> \'G Ǵ
imap <buffer> \=\`E Ḕ
imap <buffer> \'I Í
imap <buffer> \=\`O Ṑ
imap <buffer> \'K Ḱ
imap <buffer> \=\`e ḕ
imap <buffer> \'L Ĺ
imap <buffer> \=\`o ṑ
imap <buffer> \'M Ḿ
imap <buffer> \=\ae ǣ
imap <buffer> \'N Ń
imap <buffer> \={A} Ā
imap <buffer> \'O Ó
imap <buffer> \={E} Ē
imap <buffer> \'P Ṕ
imap <buffer> \={G} Ḡ
imap <buffer> \'R Ŕ
imap <buffer> \={I} Ī
imap <buffer> \'S Ś
imap <buffer> \={O} Ō
imap <buffer> \'U Ú
imap <buffer> \={U} Ū
imap <buffer> \'W Ẃ
imap <buffer> \={Y} Ȳ
imap <buffer> \'Y Ý
imap <buffer> \={a} ā
imap <buffer> \'Z Ź
imap <buffer> \={e} ē
imap <buffer> \'a á
imap <buffer> \={g} ḡ
imap <buffer> \'c ć
imap <buffer> \={i} ī
imap <buffer> \'e é
imap <buffer> \={o} ō
imap <buffer> \'g ǵ
imap <buffer> \={u} ū
imap <buffer> \'i í
imap <buffer> \={y} ȳ
imap <buffer> \'k ḱ
imap <buffer> \>~nn ≵
imap <buffer> \'l ĺ
imap <buffer> \Beta Β
imap <buffer> \'m ḿ
imap <buffer> \Heta Ͱ
imap <buffer> \'n ń
imap <buffer> \Hori Ϩ
imap <buffer> \'o ó
imap <buffer> \H{O} Ő
imap <buffer> \'p ṕ
imap <buffer> \H{U} Ű
imap <buffer> \'r ŕ
imap <buffer> \H{o} ő
imap <buffer> \'s ś
imap <buffer> \H{u} ű
imap <buffer> \'u ú
imap <buffer> \Iota Ι
imap <buffer> \'w ẃ
imap <buffer> \Join ⋈
imap <buffer> \'y ý
imap <buffer> \Khei Ϧ
imap <buffer> \'z ź
imap <buffer> \Shei Ϣ
imap <buffer> \(= ≘
imap <buffer> \U{o} ő
imap <buffer> \(b ⟅
imap <buffer> \Vert ‖
imap <buffer> \)b ⟆
imap <buffer> \Zeta Ζ
imap <buffer> \*= ≛
imap <buffer> \^\'A Ấ
imap <buffer> \+ ⊹
imap <buffer> \^\'E Ế
imap <buffer> \-: ∹
imap <buffer> \^\'O Ố
imap <buffer> \-> →
imap <buffer> \^\'a ấ
imap <buffer> \-o ⊸
imap <buffer> \^\'e ế
imap <buffer> \-<bar> ⊣
imap <buffer> \^\'o ố
imap <buffer> \-~ ≂
imap <buffer> \^\Ae ᴭ
imap <buffer> \.+ ∔
imap <buffer> \^\Ou ᴽ
imap <buffer> \.- ∸
imap <buffer> \^\`A Ầ
imap <buffer> \.= ≐
imap <buffer> \^\`E Ề
imap <buffer> \.A Ȧ
imap <buffer> \^\`O Ồ
imap <buffer> \.B Ḃ
imap <buffer> \^\`a ầ
imap <buffer> \.C Ċ
imap <buffer> \^\`e ề
imap <buffer> \.D Ḋ
imap <buffer> \^\`o ồ
imap <buffer> \.E Ė
imap <buffer> \^\~A Ẫ
imap <buffer> \.F Ḟ
imap <buffer> \^\~E Ễ
imap <buffer> \.G Ġ
imap <buffer> \^\~O Ỗ
imap <buffer> \.H Ḣ
imap <buffer> \^\~a ẫ
imap <buffer> \.I İ
imap <buffer> \^\~e ễ
imap <buffer> \.M Ṁ
imap <buffer> \^\~o ỗ
imap <buffer> \.N Ṅ
imap <buffer> \^{A} Â
imap <buffer> \.O Ȯ
imap <buffer> \^{C} Ĉ
imap <buffer> \.P Ṗ
imap <buffer> \^{E} Ê
imap <buffer> \.R Ṙ
imap <buffer> \^{G} Ĝ
imap <buffer> \.S Ṡ
imap <buffer> \^{H} Ĥ
imap <buffer> \.T Ṫ
imap <buffer> \^{I} Î
imap <buffer> \.W Ẇ
imap <buffer> \^{J} Ĵ
imap <buffer> \.X Ẋ
imap <buffer> \^{O} Ô
imap <buffer> \.Y Ẏ
imap <buffer> \^{S} Ŝ
imap <buffer> \.Z Ż
imap <buffer> \^{U} Û
imap <buffer> \.a ȧ
imap <buffer> \^{W} Ŵ
imap <buffer> \.b ḃ
imap <buffer> \^{Y} Ŷ
imap <buffer> \.c ċ
imap <buffer> \^{Z} Ẑ
imap <buffer> \.d ḋ
imap <buffer> \^{a} â
imap <buffer> \.e ė
imap <buffer> \^{c} ĉ
imap <buffer> \.f ḟ
imap <buffer> \^{e} ê
imap <buffer> \.g ġ
imap <buffer> \^{g} ĝ
imap <buffer> \.h ḣ
imap <buffer> \^{h} ĥ
imap <buffer> \.m ṁ
imap <buffer> \^{i} î
imap <buffer> \.n ṅ
imap <buffer> \^{j} ĵ
imap <buffer> \.o ȯ
imap <buffer> \^{o} ô
imap <buffer> \.p ṗ
imap <buffer> \^{s} ŝ
imap <buffer> \.r ṙ
imap <buffer> \^{u} û
imap <buffer> \.s ṡ
imap <buffer> \^{w} ŵ
imap <buffer> \.t ṫ
imap <buffer> \^{y} ŷ
imap <buffer> \.w ẇ
imap <buffer> \^{z} ẑ
imap <buffer> \.x ẋ
imap <buffer> \`{A} À
imap <buffer> \.y ẏ
imap <buffer> \`{E} È
imap <buffer> \.z ż
imap <buffer> \`{I} Ì
imap <buffer> \:: ∷
imap <buffer> \`{N} Ǹ
imap <buffer> \:= ≔
imap <buffer> \`{O} Ò
imap <buffer> \:~ ∻
imap <buffer> \`{U} Ù
imap <buffer> \<- ←
imap <buffer> \`{W} Ẁ
imap <buffer> \<< ⟪
imap <buffer> \`{Y} Ỳ
imap <buffer> \<= ≤
imap <buffer> \`{a} à
imap <buffer> \<n ≮
imap <buffer> \`{e} è
imap <buffer> \<~ ≲
imap <buffer> \`{i} ì
imap <buffer> \=: ≕
imap <buffer> \`{n} ǹ
imap <buffer> \== ≡
imap <buffer> \`{o} ò
imap <buffer> \=> ⇒
imap <buffer> \`{u} ù
imap <buffer> \=A Ā
imap <buffer> \`{w} ẁ
imap <buffer> \=E Ē
imap <buffer> \`{y} ỳ
imap <buffer> \=G Ḡ
imap <buffer> \and= ≙
imap <buffer> \=I Ī
imap <buffer> \beta β
imap <buffer> \=O Ō
imap <buffer> \beth ℶ
imap <buffer> \=U Ū
imap <buffer> \bsum ⅀
imap <buffer> \=Y Ȳ
imap <buffer> \c\'C Ḉ
imap <buffer> \=a ā
imap <buffer> \c\'c ḉ
imap <buffer> \=e ē
imap <buffer> \c\uE Ḝ
imap <buffer> \=g ḡ
imap <buffer> \c\ue ḝ
imap <buffer> \=i ī
imap <buffer> \cdot ·
imap <buffer> \=n ≠
imap <buffer> \cedi ₵
imap <buffer> \=u ū
imap <buffer> \cent ¢
imap <buffer> \=y ȳ
imap <buffer> \ci.. ◌
imap <buffer> \>= ≥
imap <buffer> \circ ∘
imap <buffer> \>> ⟫
imap <buffer> \comp ∘
imap <buffer> \>n ≯
imap <buffer> \cong ≅
imap <buffer> \>~ ≳
imap <buffer> \c{C} Ç
imap <buffer> \?= ≟
imap <buffer> \c{D} Ḑ
imap <buffer> \?? ⁇
imap <buffer> \c{E} Ȩ
imap <buffer> \AA Å
imap <buffer> \c{G} Ģ
imap <buffer> \AE Æ
imap <buffer> \c{H} Ḩ
imap <buffer> \DH Ð
imap <buffer> \c{K} Ķ
imap <buffer> \GA Α
imap <buffer> \c{L} Ļ
imap <buffer> \GB Β
imap <buffer> \c{N} Ņ
imap <buffer> \GC Χ
imap <buffer> \c{R} Ŗ
imap <buffer> \GD Δ
imap <buffer> \c{S} Ş
imap <buffer> \GE Ε
imap <buffer> \c{T} Ţ
imap <buffer> \GF Φ
imap <buffer> \c{c} ç
imap <buffer> \GG Γ
imap <buffer> \c{d} ḑ
imap <buffer> \GI Ι
imap <buffer> \c{e} ȩ
imap <buffer> \GK Κ
imap <buffer> \c{g} ģ
imap <buffer> \GL Λ
imap <buffer> \c{h} ḩ
imap <buffer> \GM Μ
imap <buffer> \c{k} ķ
imap <buffer> \GN Ν
imap <buffer> \c{l} ļ
imap <buffer> \GO Ω
imap <buffer> \c{n} ņ
imap <buffer> \GP Ψ
imap <buffer> \c{r} ŗ
imap <buffer> \GR Ρ
imap <buffer> \c{s} ş
imap <buffer> \GS Σ
imap <buffer> \c{t} ţ
imap <buffer> \GT Τ
imap <buffer> \d-u- ⇵
imap <buffer> \GU Υ
imap <buffer> \d\.S Ṩ
imap <buffer> \GX Ξ
imap <buffer> \d\.s ṩ
imap <buffer> \GZ Ζ
imap <buffer> \d\=L Ḹ
imap <buffer> \Ga α
imap <buffer> \d\=R Ṝ
imap <buffer> \Gb β
imap <buffer> \d\=l ḹ
imap <buffer> \Gc χ
imap <buffer> \d\=r ṝ
imap <buffer> \Gd δ
imap <buffer> \ddag ‡
imap <buffer> \Ge ε
imap <buffer> \def= ≝
imap <buffer> \Gf φ
imap <buffer> \defs ≙
imap <buffer> \Gg γ
imap <buffer> \dong ₫
imap <buffer> \Gi ι
imap <buffer> \d{A} Ạ
imap <buffer> \Gk κ
imap <buffer> \d{B} Ḅ
imap <buffer> \Gl λ
imap <buffer> \d{D} Ḍ
imap <buffer> \Gm μ
imap <buffer> \d{E} Ẹ
imap <buffer> \Gn ν
imap <buffer> \d{H} Ḥ
imap <buffer> \Go ω
imap <buffer> \d{I} Ị
imap <buffer> \Gp ψ
imap <buffer> \d{K} Ḳ
imap <buffer> \Gr ρ
imap <buffer> \d{L} Ḷ
imap <buffer> \Gs σ
imap <buffer> \d{M} Ṃ
imap <buffer> \Gt τ
imap <buffer> \d{N} Ṇ
imap <buffer> \Gu υ
imap <buffer> \d{O} Ọ
imap <buffer> \Gx ξ
imap <buffer> \d{R} Ṛ
imap <buffer> \Gz ζ
imap <buffer> \d{S} Ṣ
imap <buffer> \HO Ő
imap <buffer> \d{T} Ṭ
imap <buffer> \HU Ű
imap <buffer> \d{U} Ụ
imap <buffer> \Ho ő
imap <buffer> \d{V} Ṿ
imap <buffer> \Hu ű
imap <buffer> \d{W} Ẉ
imap <buffer> \Im ℑ
imap <buffer> \d{Y} Ỵ
imap <buffer> \Ll ⋘
imap <buffer> \d{Z} Ẓ
imap <buffer> \Mu Μ
imap <buffer> \d{a} ạ
imap <buffer> \Nu Ν
imap <buffer> \d{b} ḅ
imap <buffer> \O* ⍟
imap <buffer> \d{d} ḍ
imap <buffer> \O+ ⨁
imap <buffer> \d{e} ẹ
imap <buffer> \O. ⨀
imap <buffer> \d{h} ḥ
imap <buffer> \OE Œ
imap <buffer> \d{i} ị
imap <buffer> \Or ⋁
imap <buffer> \d{k} ḳ
imap <buffer> \Ox ⨂
imap <buffer> \d{l} ḷ
imap <buffer> \Pi Π
imap <buffer> \d{m} ṃ
imap <buffer> \Re ℜ
imap <buffer> \d{n} ṇ
imap <buffer> \TH Þ
imap <buffer> \d{o} ọ
imap <buffer> \U+ ⨄
imap <buffer> \d{r} ṛ
imap <buffer> \U. ⨃
imap <buffer> \d{s} ṣ
imap <buffer> \Un ⋃
imap <buffer> \d{t} ṭ
imap <buffer> \Uo ő
imap <buffer> \d{u} ụ
imap <buffer> \Xi Ξ
imap <buffer> \d{v} ṿ
imap <buffer> \[[ ⟦
imap <buffer> \d{w} ẉ
imap <buffer> \]] ⟧
imap <buffer> \d{y} ỵ
imap <buffer> \^( ⁽
imap <buffer> \d{z} ẓ
imap <buffer> \^) ⁾
imap <buffer> \euro €
imap <buffer> \^+ ⁺
imap <buffer> \flat ♭
imap <buffer> \^- ⁻
imap <buffer> \flqq «
imap <buffer> \^0 ⁰
imap <buffer> \frqq »
imap <buffer> \^1 ¹
imap <buffer> \geqq ≧
imap <buffer> \^2 ²
imap <buffer> \gets ←
imap <buffer> \^3 ³
imap <buffer> \glqq „
imap <buffer> \^4 ⁴
imap <buffer> \gneq ≩
imap <buffer> \^5 ⁵
imap <buffer> \grqq “
imap <buffer> \^6 ⁶
imap <buffer> \hbar ℏ
imap <buffer> \^7 ⁷
imap <buffer> \heta ͱ
imap <buffer> \^8 ⁸
imap <buffer> \hori ϩ
imap <buffer> \^9 ⁹
imap <buffer> \iota ι
imap <buffer> \^= ⁼
imap <buffer> \k\=O Ǭ
imap <buffer> \^B ᴮ
imap <buffer> \k\=o ǭ
imap <buffer> \^C Ĉ
imap <buffer> \khei ϧ
imap <buffer> \^D ᴰ
imap <buffer> \k{A} Ą
imap <buffer> \^K ᴷ
imap <buffer> \k{E} Ę
imap <buffer> \^L ᴸ
imap <buffer> \k{I} Į
imap <buffer> \^M ᴹ
imap <buffer> \k{O} Ǫ
imap <buffer> \^N ᴺ
imap <buffer> \k{U} Ų
imap <buffer> \^P ᴾ
imap <buffer> \k{a} ą
imap <buffer> \^R ᴿ
imap <buffer> \k{e} ę
imap <buffer> \^S Ŝ
imap <buffer> \k{i} į
imap <buffer> \^T ᵀ
imap <buffer> \k{o} ǫ
imap <buffer> \^V ⱽ
imap <buffer> \k{u} ų
imap <buffer> \^Y Ŷ
imap <buffer> \l-r- ⇆
imap <buffer> \^Z Ẑ
imap <buffer> \lbag ⟅
imap <buffer> \^b ᵇ
imap <buffer> \leqq ≦
imap <buffer> \^d ᵈ
imap <buffer> \lira ₤
imap <buffer> \^f ᶠ
imap <buffer> \lneq ≨
imap <buffer> \^k ᵏ
imap <buffer> \lnot ¬
imap <buffer> \^m ᵐ
imap <buffer> \lr-- ⟷
imap <buffer> \^n ⁿ
imap <buffer> \lr-n ↮
imap <buffer> \^p ᵖ
imap <buffer> \lr=n ⇎
imap <buffer> \^t ᵗ
imap <buffer> \male ♂
imap <buffer> \^x ˣ
imap <buffer> \mill ₥
imap <buffer> \_( ₍
imap <buffer> \ngeq ≱
imap <buffer> \_) ₎
imap <buffer> \ngtr ≯
imap <buffer> \_+ ₊
imap <buffer> \nleq ≰
imap <buffer> \_- ₋
imap <buffer> \nmid ∤
imap <buffer> \_0 ₀
imap <buffer> \nsim ≁
imap <buffer> \_1 ₁
imap <buffer> \odot ⊙
imap <buffer> \_2 ₂
imap <buffer> \oint ∮
imap <buffer> \_3 ₃
imap <buffer> \perp ⊥
imap <buffer> \_4 ₄
imap <buffer> \peso ₱
imap <buffer> \_5 ₅
imap <buffer> \prec ≺
imap <buffer> \_6 ₆
imap <buffer> \prod ∏
imap <buffer> \_7 ₇
imap <buffer> \quad  
imap <buffer> \_8 ₈
imap <buffer> \r-l- ⇄
imap <buffer> \_9 ₉
imap <buffer> \rbag ⟆
imap <buffer> \_= ₌
imap <buffer> \rial ﷼
imap <buffer> \_a ₐ
imap <buffer> \shei ϣ
imap <buffer> \_e ₑ
imap <buffer> \squb ⊏
imap <buffer> \_h ₕ
imap <buffer> \squp ⊐
imap <buffer> \_i ᵢ
imap <buffer> \st12 ✹
imap <buffer> \_j ⱼ
imap <buffer> \star ⋆
imap <buffer> \_k ₖ
imap <buffer> \sub= ⊆
imap <buffer> \_l ₗ
imap <buffer> \subn ⊄
imap <buffer> \_m ₘ
imap <buffer> \succ ≻
imap <buffer> \_n ₙ
imap <buffer> \sup= ⊇
imap <buffer> \_o ₒ
imap <buffer> \supn ⊅
imap <buffer> \_p ₚ
imap <buffer> \surd √
imap <buffer> \_r ᵣ
imap <buffer> \u-d- ⇅
imap <buffer> \_s ₛ
imap <buffer> \u\'A Ắ
imap <buffer> \_t ₜ
imap <buffer> \u\'a ắ
imap <buffer> \_u ᵤ
imap <buffer> \u\`A Ằ
imap <buffer> \_x ₓ
imap <buffer> \u\`a ằ
imap <buffer> \_~ ̰
imap <buffer> \u\~A Ẵ
imap <buffer> \`A À
imap <buffer> \u\~a ẵ
imap <buffer> \`E È
imap <buffer> \ud-<bar> ↨
imap <buffer> \`I Ì
imap <buffer> \u{A} Ă
imap <buffer> \`N Ǹ
imap <buffer> \u{E} Ĕ
imap <buffer> \`O Ò
imap <buffer> \u{G} Ğ
imap <buffer> \`U Ù
imap <buffer> \u{I} Ĭ
imap <buffer> \`W Ẁ
imap <buffer> \u{O} Ŏ
imap <buffer> \`Y Ỳ
imap <buffer> \u{U} Ŭ
imap <buffer> \`a à
imap <buffer> \u{a} ă
imap <buffer> \`e è
imap <buffer> \u{e} ĕ
imap <buffer> \`i ì
imap <buffer> \u{g} ğ
imap <buffer> \`n ǹ
imap <buffer> \u{i} ĭ
imap <buffer> \`o ò
imap <buffer> \u{o} ŏ
imap <buffer> \`u ù
imap <buffer> \u{u} ŭ
imap <buffer> \`w ẁ
imap <buffer> \v\.S Ṧ
imap <buffer> \`y ỳ
imap <buffer> \v\.s ṧ
imap <buffer> \aa å
imap <buffer> \v{A} Ǎ
imap <buffer> \ae æ
imap <buffer> \v{C} Č
imap <buffer> \b+ ⊞
imap <buffer> \v{D} Ď
imap <buffer> \b- ⊟
imap <buffer> \v{E} Ě
imap <buffer> \b. ⊡
imap <buffer> \v{G} Ǧ
imap <buffer> \b0 𝟘
imap <buffer> \v{H} Ȟ
imap <buffer> \b1 𝟙
imap <buffer> \v{I} Ǐ
imap <buffer> \b2 𝟚
imap <buffer> \v{K} Ǩ
imap <buffer> \b3 𝟛
imap <buffer> \v{L} Ľ
imap <buffer> \b4 𝟜
imap <buffer> \v{N} Ň
imap <buffer> \b5 𝟝
imap <buffer> \v{O} Ǒ
imap <buffer> \b6 𝟞
imap <buffer> \v{R} Ř
imap <buffer> \b7 𝟟
imap <buffer> \v{S} Š
imap <buffer> \b8 𝟠
imap <buffer> \v{T} Ť
imap <buffer> \b9 𝟡
imap <buffer> \v{U} Ǔ
imap <buffer> \bb 𝔹
imap <buffer> \v{Z} Ž
imap <buffer> \bc ℂ
imap <buffer> \v{a} ǎ
imap <buffer> \bn ℕ
imap <buffer> \v{c} č
imap <buffer> \bp ℙ
imap <buffer> \v{d} ď
imap <buffer> \bq ℚ
imap <buffer> \v{e} ě
imap <buffer> \br ℝ
imap <buffer> \v{g} ǧ
imap <buffer> \bx ⊠
imap <buffer> \v{h} ȟ
imap <buffer> \bz ℤ
imap <buffer> \v{i} ǐ
imap <buffer> \cC Ç
imap <buffer> \v{j} ǰ
imap <buffer> \cD Ḑ
imap <buffer> \v{k} ǩ
imap <buffer> \cE Ȩ
imap <buffer> \v{l} ľ
imap <buffer> \cG Ģ
imap <buffer> \v{n} ň
imap <buffer> \cH Ḩ
imap <buffer> \v{o} ǒ
imap <buffer> \cK Ķ
imap <buffer> \v{r} ř
imap <buffer> \cL Ļ
imap <buffer> \v{s} š
imap <buffer> \cN Ņ
imap <buffer> \v{t} ť
imap <buffer> \cR Ŗ
imap <buffer> \v{u} ǔ
imap <buffer> \cS Ş
imap <buffer> \v{z} ž
imap <buffer> \cT Ţ
imap <buffer> \zeta ζ
imap <buffer> \cc ç
imap <buffer> \<bar><bar>-n ⊮
imap <buffer> \cd ḑ
imap <buffer> \<bar><bar>=n ⊯
imap <buffer> \ce ȩ
imap <buffer> \<bar><bar><bar>- ⊪
imap <buffer> \cg ģ
imap <buffer> \~\"O Ṏ
imap <buffer> \ch ḩ
imap <buffer> \~\"o ṏ
imap <buffer> \ck ķ
imap <buffer> \~\'O Ṍ
imap <buffer> \cn ņ
imap <buffer> \~\'U Ṹ
imap <buffer> \cr ŗ
imap <buffer> \~\'o ṍ
imap <buffer> \cs ş
imap <buffer> \~\'u ṹ
imap <buffer> \ct ţ
imap <buffer> \~\=O Ȭ
imap <buffer> \d- ↓
imap <buffer> \~\=o ȭ
imap <buffer> \d= ⇓
imap <buffer> \~{A} Ã
imap <buffer> \dh ð
imap <buffer> \~{E} Ẽ
imap <buffer> \dz ↯
imap <buffer> \~{I} Ĩ
imap <buffer> \em —
imap <buffer> \~{N} Ñ
imap <buffer> \en –
imap <buffer> \~{O} Õ
imap <buffer> \ex ∃
imap <buffer> \~{U} Ũ
imap <buffer> \ge ≥
imap <buffer> \~{V} Ṽ
imap <buffer> \gg ≫
imap <buffer> \~{Y} Ỹ
imap <buffer> \in ∈
imap <buffer> \~{a} ã
imap <buffer> \kA Ą
imap <buffer> \~{e} ẽ
imap <buffer> \kE Ę
imap <buffer> \~{i} ĩ
imap <buffer> \kI Į
imap <buffer> \~{n} ñ
imap <buffer> \kO Ǫ
imap <buffer> \~{o} õ
imap <buffer> \kU Ų
imap <buffer> \~{u} ũ
imap <buffer> \ka ą
imap <buffer> \~{v} ṽ
imap <buffer> \ke ę
imap <buffer> \~{y} ỹ
imap <buffer> \ki į
imap <buffer> \'{\O} Ǿ
imap <buffer> \ko ǫ
imap <buffer> \'{\o} ǿ
imap <buffer> \ku ų
imap <buffer> \={\i} ī
imap <buffer> \l- ←
imap <buffer> \Alpha Α
imap <buffer> \l= ⇐
imap <buffer> \Delta Δ
imap <buffer> \le ≤
imap <buffer> \Gamma Γ
imap <buffer> \ll ≪
imap <buffer> \Kappa Κ
imap <buffer> \lq ‘
imap <buffer> \Koppa Ϟ
imap <buffer> \m= ≞
imap <buffer> \Lamda Λ
imap <buffer> \mp ∓
imap <buffer> \Omega Ω
imap <buffer> \mu μ
imap <buffer> \Sampi Ϡ
imap <buffer> \ne ≠
imap <buffer> \Shima Ϭ
imap <buffer> \ni ∋
imap <buffer> \Sigma Σ
imap <buffer> \nu ν
imap <buffer> \Theta Θ
imap <buffer> \o* ⊛
imap <buffer> \Vdash ⊩
imap <buffer> \o+ ⊕
imap <buffer> \^\ain ᵜ
imap <buffer> \o- ⊝
imap <buffer> \^\chi ᵡ
imap <buffer> \o. ⊙
imap <buffer> \^\eng ᵑ
imap <buffer> \o/ ⊘
imap <buffer> \^\esh ᶴ
imap <buffer> \o= ⊜
imap <buffer> \^\eth ᶞ
imap <buffer> \oe œ
imap <buffer> \^\ezh ᶾ
imap <buffer> \oo ⊚
imap <buffer> \^\phi ᶲ
imap <buffer> \or ∨
imap <buffer> \^{SM} ℠
imap <buffer> \ox ⊗
imap <buffer> \^{TM} ™
imap <buffer> \pi π
imap <buffer> \^{\j} ĵ
imap <buffer> \pm ±
imap <buffer> \aleph ℵ
imap <buffer> \r- →
imap <buffer> \alpha α
imap <buffer> \r= ⇒
imap <buffer> \amalg ∐
imap <buffer> \rq ’
imap <buffer> \asymp ≍
imap <buffer> \ss ß
imap <buffer> \cdots ⋯
imap <buffer> \t= ≜
imap <buffer> \colon ₡
imap <buffer> \th þ
imap <buffer> \dashv ⊣
imap <buffer> \to →
imap <buffer> \ddots ⋱
imap <buffer> \u+ ⊎
imap <buffer> \delta δ
imap <buffer> \u- ↑
imap <buffer> \doteq ≐
imap <buffer> \u. ⊍
imap <buffer> \equiv ≡
imap <buffer> \u= ⇑
imap <buffer> \frac1 ⅟
imap <buffer> \uA Ă
imap <buffer> \frown ⌢
imap <buffer> \uE Ĕ
imap <buffer> \gamma γ
imap <buffer> \uG Ğ
imap <buffer> \gimel ℷ
imap <buffer> \uI Ĭ
imap <buffer> \gneqq ≩
imap <buffer> \uO Ŏ
imap <buffer> \gnsim ⋧
imap <buffer> \uU Ŭ
imap <buffer> \imath ı
imap <buffer> \ua ă
imap <buffer> \infty ∞
imap <buffer> \ue ĕ
imap <buffer> \kappa κ
imap <buffer> \ug ğ
imap <buffer> \koppa ϟ
imap <buffer> \ui ĭ
imap <buffer> \lamda λ
imap <buffer> \un ∪
imap <buffer> \lceil ⌈
imap <buffer> \uo ŏ
imap <buffer> \ldata 《
imap <buffer> \uu ŭ
imap <buffer> \ldots …
imap <buffer> \vA Ǎ
imap <buffer> \lneqq ≨
imap <buffer> \vC Č
imap <buffer> \lnsim ⋦
imap <buffer> \vD Ď
imap <buffer> \micro µ
imap <buffer> \vE Ě
imap <buffer> \minus −
imap <buffer> \vG Ǧ
imap <buffer> \nabla ∇
imap <buffer> \vH Ȟ
imap <buffer> \naira ₦
imap <buffer> \vI Ǐ
imap <buffer> \ncong ≇
imap <buffer> \vK Ǩ
imap <buffer> \ngeqq ≱
imap <buffer> \vL Ľ
imap <buffer> \nleqq ≰
imap <buffer> \vN Ň
imap <buffer> \nless ≮
imap <buffer> \vO Ǒ
imap <buffer> \notin ∉
imap <buffer> \vR Ř
imap <buffer> \nprec ⊀
imap <buffer> \vS Š
imap <buffer> \nsucc ⊁
imap <buffer> \vT Ť
imap <buffer> \omega ω
imap <buffer> \vU Ǔ
imap <buffer> \oplus ⊕
imap <buffer> \vZ Ž
imap <buffer> \ounce ℥
imap <buffer> \va ǎ
imap <buffer> \pound £
imap <buffer> \vc č
imap <buffer> \prime ′
imap <buffer> \vd ď
imap <buffer> \rceil ⌉
imap <buffer> \ve ě
imap <buffer> \rdata 》
imap <buffer> \vg ǧ
imap <buffer> \rupee ₨
imap <buffer> \vh ȟ
imap <buffer> \sampi ϡ
imap <buffer> \vi ǐ
imap <buffer> \sharp ♯
imap <buffer> \vj ǰ
imap <buffer> \shima ϭ
imap <buffer> \vk ǩ
imap <buffer> \sigma σ
imap <buffer> \vl ľ
imap <buffer> \simeq ≃
imap <buffer> \vn ň
imap <buffer> \smile ⌣
imap <buffer> \vo ǒ
imap <buffer> \sqcap ⊓
imap <buffer> \vr ř
imap <buffer> \sqcup ⊔
imap <buffer> \vs š
imap <buffer> \squb= ⊑
imap <buffer> \vt ť
imap <buffer> \squp= ⊒
imap <buffer> \vu ǔ
imap <buffer> \sub=n ⊈
imap <buffer> \vz ž
imap <buffer> \sup=n ⊉
imap <buffer> \wp ℘
imap <buffer> \surd3 ∛
imap <buffer> \wr ≀
imap <buffer> \surd4 ∜
imap <buffer> \xi ξ
imap <buffer> \tenge ₸
imap <buffer> \{{ ⦃
imap <buffer> \theta θ
imap <buffer> \<bar>- ⊢
imap <buffer> \times ×
imap <buffer> \<bar>= ⊨
imap <buffer> \uplus ⊎
imap <buffer> \<bar>n ∤
imap <buffer> \u{\i} ĭ
imap <buffer> \<bar><bar> ∥
imap <buffer> \vDash ⊨
imap <buffer> \}} ⦄
imap <buffer> \varpi ϖ
imap <buffer> \~- ≃
imap <buffer> \vdash ⊢
imap <buffer> \~= ≅
imap <buffer> \vdots ⋮
imap <buffer> \~A Ã
imap <buffer> \v{\i} ǐ
imap <buffer> \~E Ẽ
imap <buffer> \v{\j} ǰ
imap <buffer> \~I Ĩ
imap <buffer> \wedge ∧
imap <buffer> \~N Ñ
imap <buffer> \~{\i} ĩ
imap <buffer> \~O Õ
imap <buffer> \"\'{I} Ḯ
imap <buffer> \~U Ũ
imap <buffer> \"\'{U} Ǘ
imap <buffer> \~V Ṽ
imap <buffer> \"\'{i} ḯ
imap <buffer> \~Y Ỹ
imap <buffer> \"\'{u} ǘ
imap <buffer> \~a ã
imap <buffer> \"\={A} Ǟ
imap <buffer> \~e ẽ
imap <buffer> \"\={O} Ȫ
imap <buffer> \~i ĩ
imap <buffer> \"\={U} Ǖ
imap <buffer> \~o õ
imap <buffer> \"\={a} ǟ
imap <buffer> \~u ũ
imap <buffer> \"\={o} ȫ
imap <buffer> \~v ṽ
imap <buffer> \"\={u} ǖ
imap <buffer> \~y ỹ
imap <buffer> \"\`{U} Ǜ
imap <buffer> \~~ ≈
imap <buffer> \"\`{u} ǜ
imap <buffer> \"{} ¨
imap <buffer> \"\v{U} Ǚ
imap <buffer> \'\O Ǿ
imap <buffer> \"\v{u} ǚ
imap <buffer> \'\o ǿ
imap <buffer> \'\.{S} Ṥ
imap <buffer> \'{} ´
imap <buffer> \'\.{s} ṥ
imap <buffer> \(0) ⓪
imap <buffer> \'{\AE} Ǽ
imap <buffer> \--> ⟶
imap <buffer> \'{\ae} ǽ
imap <buffer> \->n ↛
imap <buffer> \.\={A} Ǡ
imap <buffer> \.=. ≑
imap <buffer> \.\={O} Ȱ
imap <buffer> \.{} ˙
imap <buffer> \.\={a} ǡ
imap <buffer> \::- ∺
imap <buffer> \.\={o} ȱ
imap <buffer> \<-- ⟵
imap <buffer> \=\"{U} Ṻ
imap <buffer> \<-> ↔
imap <buffer> \=\"{u} ṻ
imap <buffer> \<-n ↚
imap <buffer> \=\'{E} Ḗ
imap <buffer> \<=> ⇔
imap <buffer> \=\'{O} Ṓ
imap <buffer> \<=n ≰
imap <buffer> \=\'{e} ḗ
imap <buffer> \<~n ⋦
imap <buffer> \=\'{o} ṓ
imap <buffer> \=== ≣
imap <buffer> \=\`{E} Ḕ
imap <buffer> \==n ≢
imap <buffer> \=\`{O} Ṑ
imap <buffer> \=>n ⇏
imap <buffer> \=\`{e} ḕ
imap <buffer> \={} ¯
imap <buffer> \=\`{o} ṑ
imap <buffer> \>=n ≱
imap <buffer> \={\AE} Ǣ
imap <buffer> \>~n ⋧
imap <buffer> \={\ae} ǣ
imap <buffer> \And ⋀
imap <buffer> \Bbb{N} ℕ
imap <buffer> \Box □
imap <buffer> \Bbb{P} ℙ
imap <buffer> \Cap ⋒
imap <buffer> \Bbb{R} ℝ
imap <buffer> \Chi Χ
imap <buffer> \Bbb{Z} ℤ
imap <buffer> \Cup ⋓
imap <buffer> \Bumpeq ≎
imap <buffer> \Dei Ϯ
imap <buffer> \Frowny ☹
imap <buffer> \Eta Η
imap <buffer> \Gangia Ϫ
imap <buffer> \Fei Ϥ
imap <buffer> \Lambda Λ
imap <buffer> \GTH Θ
imap <buffer> \Letter ✉
imap <buffer> \Gl- ƛ
imap <buffer> \Smiley ☺
imap <buffer> \Glb ⨅
imap <buffer> \Stigma Ϛ
imap <buffer> \Gth θ
imap <buffer> \Subset ⋐
imap <buffer> \H{} ˝
imap <buffer> \Supset ⋑
imap <buffer> \Lsh ↰
imap <buffer> \Vvdash ⊪
imap <buffer> \Lub ⨆
imap <buffer> \^\'{A} Ấ
imap <buffer> \MCA 𝓐
imap <buffer> \^\'{E} Ế
imap <buffer> \MCB 𝓑
imap <buffer> \^\'{O} Ố
imap <buffer> \MCC 𝓒
imap <buffer> \^\'{a} ấ
imap <buffer> \MCD 𝓓
imap <buffer> \^\'{e} ế
imap <buffer> \MCE 𝓔
imap <buffer> \^\'{o} ố
imap <buffer> \MCF 𝓕
imap <buffer> \^\`{A} Ầ
imap <buffer> \MCG 𝓖
imap <buffer> \^\`{E} Ề
imap <buffer> \MCH 𝓗
imap <buffer> \^\`{O} Ồ
imap <buffer> \MCI 𝓘
imap <buffer> \^\`{a} ầ
imap <buffer> \MCJ 𝓙
imap <buffer> \^\`{e} ề
imap <buffer> \MCK 𝓚
imap <buffer> \^\`{o} ồ
imap <buffer> \MCL 𝓛
imap <buffer> \^\beta ᵝ
imap <buffer> \MCM 𝓜
imap <buffer> \^\d{A} Ậ
imap <buffer> \MCN 𝓝
imap <buffer> \^\d{E} Ệ
imap <buffer> \MCO 𝓞
imap <buffer> \^\d{O} Ộ
imap <buffer> \MCP 𝓟
imap <buffer> \^\d{a} ậ
imap <buffer> \MCQ 𝓠
imap <buffer> \^\d{e} ệ
imap <buffer> \MCR 𝓡
imap <buffer> \^\d{o} ộ
imap <buffer> \MCS 𝓢
imap <buffer> \^\iota ᶥ
imap <buffer> \MCT 𝓣
imap <buffer> \^\~{A} Ẫ
imap <buffer> \MCU 𝓤
imap <buffer> \^\~{E} Ễ
imap <buffer> \MCV 𝓥
imap <buffer> \^\~{O} Ỗ
imap <buffer> \MCW 𝓦
imap <buffer> \^\~{a} ẫ
imap <buffer> \MCX 𝓧
imap <buffer> \^\~{e} ễ
imap <buffer> \MCY 𝓨
imap <buffer> \^\~{o} ỗ
imap <buffer> \MCZ 𝓩
imap <buffer> \^{TEL} ℡
imap <buffer> \MCa 𝓪
imap <buffer> \approx ≈
imap <buffer> \MCb 𝓫
imap <buffer> \bigcap ⋂
imap <buffer> \MCc 𝓬
imap <buffer> \bigcup ⋃
imap <buffer> \MCd 𝓭
imap <buffer> \bigvee ⋁
imap <buffer> \MCe 𝓮
imap <buffer> \bowtie ⋈
imap <buffer> \MCf 𝓯
imap <buffer> \bumpeq ≏
imap <buffer> \MCg 𝓰
imap <buffer> \c\'{C} Ḉ
imap <buffer> \MCh 𝓱
imap <buffer> \c\'{c} ḉ
imap <buffer> \MCi 𝓲
imap <buffer> \c\u{E} Ḝ
imap <buffer> \MCj 𝓳
imap <buffer> \c\u{e} ḝ
imap <buffer> \MCk 𝓴
imap <buffer> \circeq ≗
imap <buffer> \MCl 𝓵
imap <buffer> \coprod ∐
imap <buffer> \MCm 𝓶
imap <buffer> \d\.{S} Ṩ
imap <buffer> \MCn 𝓷
imap <buffer> \d\.{s} ṩ
imap <buffer> \MCo 𝓸
imap <buffer> \d\={L} Ḹ
imap <buffer> \MCp 𝓹
imap <buffer> \d\={R} Ṝ
imap <buffer> \MCq 𝓺
imap <buffer> \d\={l} ḹ
imap <buffer> \MCr 𝓻
imap <buffer> \d\={r} ṝ
imap <buffer> \MCs 𝓼
imap <buffer> \dagger †
imap <buffer> \MCt 𝓽
imap <buffer> \daleth ℸ
imap <buffer> \MCu 𝓾
imap <buffer> \degree °
imap <buffer> \MCv 𝓿
imap <buffer> \eqcirc ≖
imap <buffer> \MCw 𝔀
imap <buffer> \exists ∃
imap <buffer> \MCx 𝔁
imap <buffer> \female ♀
imap <buffer> \MCy 𝔂
imap <buffer> \forall ∀
imap <buffer> \MCz 𝔃
imap <buffer> \frac12 ½
imap <buffer> \MIA 𝑨
imap <buffer> \frac13 ⅓
imap <buffer> \MIB 𝑩
imap <buffer> \frac14 ¼
imap <buffer> \MIC 𝑪
imap <buffer> \frac15 ⅕
imap <buffer> \MID 𝑫
imap <buffer> \frac16 ⅙
imap <buffer> \MIE 𝑬
imap <buffer> \frac18 ⅛
imap <buffer> \MIF 𝑭
imap <buffer> \frac23 ⅔
imap <buffer> \MIG 𝑮
imap <buffer> \frac25 ⅖
imap <buffer> \MIH 𝑯
imap <buffer> \frac34 ¾
imap <buffer> \MII 𝑰
imap <buffer> \frac35 ⅗
imap <buffer> \MIJ 𝑱
imap <buffer> \frac38 ⅜
imap <buffer> \MIK 𝑲
imap <buffer> \frac45 ⅘
imap <buffer> \MIL 𝑳
imap <buffer> \frac56 ⅚
imap <buffer> \MIM 𝑴
imap <buffer> \frac58 ⅝
imap <buffer> \MIN 𝑵
imap <buffer> \frac78 ⅞
imap <buffer> \MIO 𝑶
imap <buffer> \gangia ϫ
imap <buffer> \MIP 𝑷
imap <buffer> \gtrdot ⋗
imap <buffer> \MIQ 𝑸
imap <buffer> \gtrsim ≳
imap <buffer> \MIR 𝑹
imap <buffer> \k\={O} Ǭ
imap <buffer> \MIS 𝑺
imap <buffer> \k\={o} ǭ
imap <buffer> \MIT 𝑻
imap <buffer> \kelvin K
imap <buffer> \MIU 𝑼
imap <buffer> \lambda λ
imap <buffer> \MIV 𝑽
imap <buffer> \langle ⟨
imap <buffer> \MIW 𝑾
imap <buffer> \lfloor ⌊
imap <buffer> \MIX 𝑿
imap <buffer> \ltimes ⋉
imap <buffer> \MIY 𝒀
imap <buffer> \mapsto ↦
imap <buffer> \MIZ 𝒁
imap <buffer> \models ⊧
imap <buffer> \MIa 𝒂
imap <buffer> \nVDash ⊯
imap <buffer> \MIb 𝒃
imap <buffer> \nVdash ⊮
imap <buffer> \MIc 𝒄
imap <buffer> \nequiv ≢
imap <buffer> \MId 𝒅
imap <buffer> \nsimeq ≄
imap <buffer> \MIe 𝒆
imap <buffer> \numero №
imap <buffer> \MIf 𝒇
imap <buffer> \nvDash ⊭
imap <buffer> \MIg 𝒈
imap <buffer> \nvdash ⊬
imap <buffer> \MIh 𝒉
imap <buffer> \ominus ⊖
imap <buffer> \MIi 𝒊
imap <buffer> \oslash ⊘
imap <buffer> \MIj 𝒋
imap <buffer> \otimes ⊗
imap <buffer> \MIk 𝒌
imap <buffer> \permil ‰
imap <buffer> \MIl 𝒍
imap <buffer> \peseta ₧
imap <buffer> \MIm 𝒎
imap <buffer> \pounds £
imap <buffer> \MIn 𝒏
imap <buffer> \preceq ≼
imap <buffer> \MIo 𝒐
imap <buffer> \propto ∝
imap <buffer> \MIp 𝒑
imap <buffer> \rangle ⟩
imap <buffer> \MIq 𝒒
imap <buffer> \rfloor ⌋
imap <buffer> \MIr 𝒓
imap <buffer> \rtimes ⋊
imap <buffer> \MIs 𝒔
imap <buffer> \square □
imap <buffer> \MIt 𝒕
imap <buffer> \squb=n ⋢
imap <buffer> \MIu 𝒖
imap <buffer> \squp=n ⋣
imap <buffer> \MIv 𝒗
imap <buffer> \stigma ϛ
imap <buffer> \MIw 𝒘
imap <buffer> \subset ⊂
imap <buffer> \MIx 𝒙
imap <buffer> \succeq ≽
imap <buffer> \MIy 𝒚
imap <buffer> \supset ⊃
imap <buffer> \MIz 𝒛
imap <buffer> \textmu µ
imap <buffer> \McA 𝒜
imap <buffer> \tugrik ₮
imap <buffer> \McC 𝒞
imap <buffer> \u\'{A} Ắ
imap <buffer> \McD 𝒟
imap <buffer> \u\'{a} ắ
imap <buffer> \McG 𝒢
imap <buffer> \u\`{A} Ằ
imap <buffer> \McJ 𝒥
imap <buffer> \u\`{a} ằ
imap <buffer> \McK 𝒦
imap <buffer> \u\d{A} Ặ
imap <buffer> \McN 𝒩
imap <buffer> \u\d{a} ặ
imap <buffer> \McO 𝒪
imap <buffer> \u\~{A} Ẵ
imap <buffer> \McP 𝒫
imap <buffer> \u\~{a} ẵ
imap <buffer> \McQ 𝒬
imap <buffer> \v\.{S} Ṧ
imap <buffer> \McS 𝒮
imap <buffer> \v\.{s} ṧ
imap <buffer> \McT 𝒯
imap <buffer> \varkai ϗ
imap <buffer> \McU 𝒰
imap <buffer> \varphi ϕ
imap <buffer> \McV 𝒱
imap <buffer> \varrho ϱ
imap <buffer> \McW 𝒲
imap <buffer> \veebar ⊻
imap <buffer> \McX 𝒳
imap <buffer> \~\"{O} Ṏ
imap <buffer> \McY 𝒴
imap <buffer> \~\"{o} ṏ
imap <buffer> \McZ 𝒵
imap <buffer> \~\'{O} Ṍ
imap <buffer> \Mca 𝒶
imap <buffer> \~\'{U} Ṹ
imap <buffer> \Mcb 𝒷
imap <buffer> \~\'{o} ṍ
imap <buffer> \Mcc 𝒸
imap <buffer> \~\'{u} ṹ
imap <buffer> \Mcd 𝒹
imap <buffer> \~\={O} Ȭ
imap <buffer> \Mcf 𝒻
imap <buffer> \~\={o} ȭ
imap <buffer> \Mch 𝒽
imap <buffer> \Diamond ◇
imap <buffer> \Mci 𝒾
imap <buffer> \Digamma Ϝ
imap <buffer> \Mcj 𝒿
imap <buffer> \Epsilon Ε
imap <buffer> \Mck 𝓀
imap <buffer> \Omicron Ο
imap <buffer> \Mcl 𝓁
imap <buffer> \Uparrow ⇑
imap <buffer> \Mcm 𝓂
imap <buffer> \Upsilon Υ
imap <buffer> \Mcn 𝓃
imap <buffer> \^\alpha ᵅ
imap <buffer> \Mcp 𝓅
imap <buffer> \^\delta ᵟ
imap <buffer> \Mcq 𝓆
imap <buffer> \^\gamma ˠ
imap <buffer> \Mcr 𝓇
imap <buffer> \^\schwa ᵊ
imap <buffer> \Mcs 𝓈
imap <buffer> \^\theta ᶿ
imap <buffer> \Mct 𝓉
imap <buffer> \^\u bar ᶶ
imap <buffer> \Mcu 𝓊
imap <buffer> \afghani ؋
imap <buffer> \Mcv 𝓋
imap <buffer> \austral ₳
imap <buffer> \Mcw 𝓌
imap <buffer> \backsim ∽
imap <buffer> \Mcx 𝓍
imap <buffer> \because ∵
imap <buffer> \Mcy 𝓎
imap <buffer> \between ≬
imap <buffer> \Mcz 𝓏
imap <buffer> \bigcirc ◯
imap <buffer> \MfA 𝔄
imap <buffer> \bigstar ★
imap <buffer> \MfB 𝔅
imap <buffer> \boxplus ⊞
imap <buffer> \MfD 𝔇
imap <buffer> \caution ☡
imap <buffer> \MfE 𝔈
imap <buffer> \celsius ℃
imap <buffer> \MfF 𝔉
imap <buffer> \coloneq ≔
imap <buffer> \MfG 𝔊
imap <buffer> \ddagger ‡
imap <buffer> \MfJ 𝔍
imap <buffer> \diamond ⋄
imap <buffer> \MfK 𝔎
imap <buffer> \digamma ϝ
imap <buffer> \MfL 𝔏
imap <buffer> \dotplus ∔
imap <buffer> \MfM 𝔐
imap <buffer> \drachma ₯
imap <buffer> \MfN 𝔑
imap <buffer> \epsilon ε
imap <buffer> \MfO 𝔒
imap <buffer> \eqcolon ≕
imap <buffer> \MfP 𝔓
imap <buffer> \gtrless ≷
imap <buffer> \MfQ 𝔔
imap <buffer> \guarani ₲
imap <buffer> \MfS 𝔖
imap <buffer> \hryvnia ₴
imap <buffer> \MfT 𝔗
imap <buffer> \leadsto ↝
imap <buffer> \MfU 𝔘
imap <buffer> \lessdot ⋖
imap <buffer> \MfV 𝔙
imap <buffer> \lessgtr ≶
imap <buffer> \MfW 𝔚
imap <buffer> \lesssim ≲
imap <buffer> \MfX 𝔛
imap <buffer> \lozenge ✧
imap <buffer> \MfY 𝔜
imap <buffer> \maltese ✠
imap <buffer> \Mfa 𝔞
imap <buffer> \napprox ≉
imap <buffer> \Mfb 𝔟
imap <buffer> \natural ♮
imap <buffer> \Mfc 𝔠
imap <buffer> \nearrow ↗
imap <buffer> \Mfd 𝔡
imap <buffer> \Mfe 𝔢
imap <buffer> \nexists ∄
imap <buffer> \Mff 𝔣
imap <buffer> \npreceq ⋠
imap <buffer> \Mfg 𝔤
imap <buffer> \nsubset ⊄
imap <buffer> \Mfh 𝔥
imap <buffer> \nsucceq ⋡
imap <buffer> \Mfi 𝔦
imap <buffer> \nsupset ⊅
imap <buffer> \Mfj 𝔧
imap <buffer> \nwarrow ↖
imap <buffer> \Mfk 𝔨
imap <buffer> \omicron ο
imap <buffer> \Mfl 𝔩
imap <buffer> \partial ∂
imap <buffer> \Mfm 𝔪
imap <buffer> \pilcrow ¶
imap <buffer> \Mfn 𝔫
imap <buffer> \precsim ≾
imap <buffer> \Mfo 𝔬
imap <buffer> \searrow ↘
imap <buffer> \Mfp 𝔭
imap <buffer> \section §
imap <buffer> \Mfq 𝔮
imap <buffer> \succsim ≿
imap <buffer> \Mfr 𝔯
imap <buffer> \swarrow ↙
imap <buffer> \Mfs 𝔰
imap <buffer> \textwon ₩
imap <buffer> \Mft 𝔱
imap <buffer> \uparrow ↑
imap <buffer> \Mfu 𝔲
imap <buffer> \upsilon υ
imap <buffer> \Mfv 𝔳
imap <buffer> \varbeta ϐ
imap <buffer> \Mfw 𝔴
imap <buffer> \warning ⚠
imap <buffer> \Mfx 𝔵
imap <buffer> \^\h hook ʱ
imap <buffer> \Mfy 𝔶
imap <buffer> \^\open e ᵋ
imap <buffer> \Mfz 𝔷
imap <buffer> \^\open o ᵓ
imap <buffer> \MiA 𝐴
imap <buffer> \angstrom Å
imap <buffer> \MiB 𝐵
imap <buffer> \approxeq ≊
imap <buffer> \MiC 𝐶
imap <buffer> \backcong ≌
imap <buffer> \MiD 𝐷
imap <buffer> \barwedge ⊼
imap <buffer> \MiE 𝐸
imap <buffer> \bigwedge ⋀
imap <buffer> \MiF 𝐹
imap <buffer> \boxminus ⊟
imap <buffer> \MiG 𝐺
imap <buffer> \boxtimes ⊠
imap <buffer> \MiH 𝐻
imap <buffer> \circledR ®
imap <buffer> \MiI 𝐼
imap <buffer> \circledS Ⓢ
imap <buffer> \MiJ 𝐽
imap <buffer> \clubsuit ♣
imap <buffer> \MiK 𝐾
imap <buffer> \cruzeiro ₢
imap <buffer> \MiL 𝐿
imap <buffer> \curlyvee ⋎
imap <buffer> \MiM 𝑀
imap <buffer> \currency ¤
imap <buffer> \MiN 𝑁
imap <buffer> \diameter ⌀
imap <buffer> \MiO 𝑂
imap <buffer> \division ÷
imap <buffer> \MiP 𝑃
imap <buffer> \doteqdot ≑
imap <buffer> \MiQ 𝑄
imap <buffer> \emptyset ∅
imap <buffer> \MiR 𝑅
imap <buffer> \geqslant ≥
imap <buffer> \MiS 𝑆
imap <buffer> \gnapprox ⋧
imap <buffer> \MiT 𝑇
imap <buffer> \intercal ⊺
imap <buffer> \MiU 𝑈
imap <buffer> \leqslant ≤
imap <buffer> \MiV 𝑉
imap <buffer> \llcorner ⌞
imap <buffer> \MiW 𝑊
imap <buffer> \lnapprox ⋦
imap <buffer> \MiX 𝑋
imap <buffer> \lrcorner ⌟
imap <buffer> \MiY 𝑌
imap <buffer> \multimap ⊸
imap <buffer> \MiZ 𝑍
imap <buffer> \parallel ∥
imap <buffer> \Mia 𝑎
imap <buffer> \precnsim ⋨
imap <buffer> \Mib 𝑏
imap <buffer> \setminus ∖
imap <buffer> \Mic 𝑐
imap <buffer> \shortmid ∣
imap <buffer> \Mid 𝑑
imap <buffer> \spesmilo ₷
imap <buffer> \Mie 𝑒
imap <buffer> \sqsubset ⊏
imap <buffer> \Mif 𝑓
imap <buffer> \sqsupset ⊐
imap <buffer> \Mig 𝑔
imap <buffer> \subseteq ⊆
imap <buffer> \Mii 𝑖
imap <buffer> \succnsim ⋩
imap <buffer> \Mij 𝑗
imap <buffer> \supseteq ⊇
imap <buffer> \Mik 𝑘
imap <buffer> \textbaht ฿
imap <buffer> \Mil 𝑙
imap <buffer> \textdied ✝
imap <buffer> \Mim 𝑚
imap <buffer> \textlira ₤
imap <buffer> \Min 𝑛
imap <buffer> \textpeso ₱
imap <buffer> \Mio 𝑜
imap <buffer> \thicksim ∼
imap <buffer> \Mip 𝑝
imap <buffer> \triangle ▵
imap <buffer> \Miq 𝑞
imap <buffer> \ulcorner ⌜
imap <buffer> \Mir 𝑟
imap <buffer> \undertie ‿
imap <buffer> \Mis 𝑠
imap <buffer> \urcorner ⌝
imap <buffer> \Mit 𝑡
imap <buffer> \varkappa ϰ
imap <buffer> \Miu 𝑢
imap <buffer> \varprime ′
imap <buffer> \Miv 𝑣
imap <buffer> \varsigma ς
imap <buffer> \Miw 𝑤
imap <buffer> \vartheta ϑ
imap <buffer> \Mix 𝑥
imap <buffer> \Downarrow ⇓
imap <buffer> \Miy 𝑦
imap <buffer> \Leftarrow ⇐
imap <buffer> \Miz 𝑧
imap <buffer> \^\upsilon ᶷ
imap <buffer> \Phi Φ
imap <buffer> \backprime ‵
imap <buffer> \Psi Ψ
imap <buffer> \backsimeq ⋍
imap <buffer> \Rho Ρ
imap <buffer> \biohazard ☣
imap <buffer> \Rsh ↱
imap <buffer> \brokenbar ¦
imap <buffer> \San Ϻ
imap <buffer> \centerdot ·
imap <buffer> \Sho Ϸ
imap <buffer> \checkmark ✓
imap <buffer> \Tau Τ
imap <buffer> \copyright ©
imap <buffer> \^a_ ª
imap <buffer> \dotsquare ⊡
imap <buffer> \^l- ⃖
imap <buffer> \downarrow ↓
imap <buffer> \^lr ⃡
imap <buffer> \facsimile ℻
imap <buffer> \^o_ º
imap <buffer> \gtrapprox ≳
imap <buffer> \^r- ⃗
imap <buffer> \gtreqless ⋛
imap <buffer> \_lr ͍
imap <buffer> \gvertneqq ≩
imap <buffer> \all ∀
imap <buffer> \heartsuit ♥
imap <buffer> \and ∧
imap <buffer> \increment ∆
imap <buffer> \ast ∗
imap <buffer> \lambdabar ƛ
imap <buffer> \bot ⊥
imap <buffer> \leftarrow ←
imap <buffer> \bub •
imap <buffer> \lesseqgtr ⋚
imap <buffer> \but ‣
imap <buffer> \llbracket 〚
imap <buffer> \buw ◦
imap <buffer> \lvertneqq ≨
imap <buffer> \cap ∩
imap <buffer> \ngeqslant ≱
imap <buffer> \chi χ
imap <buffer> \nleqslant ≰
imap <buffer> \ci. ◎
imap <buffer> \nparallel ∦
imap <buffer> \ciO ◯
imap <buffer> \nshortmid ∤
imap <buffer> \cib ●
imap <buffer> \nsubseteq ⊈
imap <buffer> \ciw ○
imap <buffer> \nsupseteq ⊉
imap <buffer> \clL ⌊
imap <buffer> \paragraph ¶
imap <buffer> \clR ⌋
imap <buffer> \pitchfork ⋔
imap <buffer> \cll ⌞
imap <buffer> \rrbracket 〛
imap <buffer> \clr ⌟
imap <buffer> \spadesuit ♠
imap <buffer> \cuL ⌈
imap <buffer> \subseteqq ⊆
imap <buffer> \cuR ⌉
imap <buffer> \subsetneq ⊊
imap <buffer> \cul ⌜
imap <buffer> \supseteqq ⊇
imap <buffer> \cup ∪
imap <buffer> \supsetneq ⊋
imap <buffer> \cur ⌝
imap <buffer> \telephone ℡
imap <buffer> \c{} ¸
imap <buffer> \textnaira ₦
imap <buffer> \d-2 ⇊
imap <buffer> \therefore ∴
imap <buffer> \d-<bar> ↧
imap <buffer> \triangleq ≜
imap <buffer> \d== ⟱
imap <buffer> \varpropto ∝
imap <buffer> \dag †
imap <buffer> \Lleftarrow ⇚
imap <buffer> \dd- ↡
imap <buffer> \Rightarrow ⇒
imap <buffer> \dei ϯ
imap <buffer> \^\Barred B ᴯ
imap <buffer> \di. ◈
imap <buffer> \^\barred o ᶱ
imap <buffer> \dib ◆
imap <buffer> \^\script g ᶢ
imap <buffer> \div ÷
imap <buffer> \^\turned a ᵄ
imap <buffer> \diw ◇
imap <buffer> \^\turned h ᶣ
imap <buffer> \dl- ↙
imap <buffer> \^\turned i ᵎ
imap <buffer> \dl= ⇙
imap <buffer> \^\turned m ᵚ
imap <buffer> \dr- ↘
imap <buffer> \^\turned r ʴ
imap <buffer> \dr= ⇘
imap <buffer> \^\turned v ᶺ
imap <buffer> \ell ℓ
imap <buffer> \circledast ⊛
imap <buffer> \eta η
imap <buffer> \complement ∁
imap <buffer> \exn ∄
imap <buffer> \curlywedge ⋏
imap <buffer> \fei ϥ
imap <buffer> \eqslantgtr ⋝
imap <buffer> \flq ‹
imap <buffer> \gtreqqless ⋛
imap <buffer> \frq ›
imap <buffer> \lessapprox ≲
imap <buffer> \gen ≱
imap <buffer> \lesseqqgtr ⋚
imap <buffer> \ggg ⋙
imap <buffer> \longmapsto ↦
imap <buffer> \glb ⊓
imap <buffer> \mathscr{I} ℐ
imap <buffer> \glq ‚
imap <buffer> \nLeftarrow ⇍
imap <buffer> \grq ‘
imap <buffer> \nleftarrow ↚
imap <buffer> \iff ⇔
imap <buffer> \nsubseteqq ⊈
imap <buffer> \inf ∞
imap <buffer> \nsupseteqq ⊉
imap <buffer> \inn ∉
imap <buffer> \precapprox ≾
imap <buffer> \int ∫
imap <buffer> \registered ®
imap <buffer> \kip ₭
imap <buffer> \rightarrow →
imap <buffer> \k{} ˛
imap <buffer> \smallamalg ∐
imap <buffer> \l-- ⟵
imap <buffer> \smallsmile ⌣
imap <buffer> \l-2 ⇇
imap <buffer> \sqsubseteq ⊑
imap <buffer> \l-> ↢
imap <buffer> \sqsupseteq ⊒
imap <buffer> \l-n ↚
imap <buffer> \subsetneqq ⊊
imap <buffer> \l-<bar> ↤
imap <buffer> \succapprox ≿
imap <buffer> \l== ⇚
imap <buffer> \supsetneqq ⊋
imap <buffer> \l=n ⇍
imap <buffer> \textlquill ⁅
imap <buffer> \ldq “
imap <buffer> \textnumero №
imap <buffer> \len ≰
imap <buffer> \textrecipe ℞
imap <buffer> \lhd ◁
imap <buffer> \textrquill ⁆
imap <buffer> \ll- ↞
imap <buffer> \upuparrows ⇈
imap <buffer> \lr- ↔
imap <buffer> \Rrightarrow ⇛
imap <buffer> \lr= ⇔
imap <buffer> \Updownarrow ⇕
imap <buffer> \lr~ ↭
imap <buffer> \^\capital i ᶦ
imap <buffer> \lub ⊔
imap <buffer> \^\capital l ᶫ
imap <buffer> \mho ℧
imap <buffer> \^\capital n ᶰ
imap <buffer> \mid ∣
imap <buffer> \^\capital u ᶸ
imap <buffer> \neg ¬
imap <buffer> \^\greek phi ᵠ
imap <buffer> \neq ≠
imap <buffer> \^\turned ae ᵆ
imap <buffer> \nin ∌
imap <buffer> \backepsilon ∍
imap <buffer> \not ̸
imap <buffer> \blacksmiley ☻
imap <buffer> \o-- ⊖
imap <buffer> \blacksquare ▪
imap <buffer> \ohm Ω
imap <buffer> \circledcirc ⊚
imap <buffer> \or= ≚
imap <buffer> \circleddash ⊝
imap <buffer> \pab ▰
imap <buffer> \curlyeqprec ⋞
imap <buffer> \paw ▱
imap <buffer> \curlyeqsucc ⋟
imap <buffer> \per ⅌
imap <buffer> \curlypreceq ≼
imap <buffer> \phi φ
imap <buffer> \diamondsuit ♢
imap <buffer> \psi ψ
imap <buffer> \eqslantless ⋜
imap <buffer> \qed ∎
imap <buffer> \nRightarrow ⇏
imap <buffer> \r-- ⟶
imap <buffer> \nrightarrow ↛
imap <buffer> \r-2 ⇉
imap <buffer> \ordfeminine ª
imap <buffer> \r-3 ⇶
imap <buffer> \partnership ㉐
imap <buffer> \r-> ↣
imap <buffer> \precnapprox ⋨
imap <buffer> \r-n ↛
imap <buffer> \radioactive ☢
imap <buffer> \r-o ⊸
imap <buffer> \straightphi φ
imap <buffer> \r-<bar> ↦
imap <buffer> \succcurlyeq ≽
imap <buffer> \r== ⇛
imap <buffer> \succnapprox ⋩
imap <buffer> \r=n ⇏
imap <buffer> \thickapprox ≈
imap <buffer> \rdq ”
imap <buffer> \updownarrow ↕
imap <buffer> \rhd ▷
imap <buffer> \^\Reversed E ᴲ
imap <buffer> \rho ρ
imap <buffer> \^\Reversed N ᴻ
imap <buffer> \rr- ↠
imap <buffer> \^\sideways u ᵙ
imap <buffer> \san ϻ
imap <buffer> \^\top half o ᵔ
imap <buffer> \sbs ﹨
imap <buffer> \blacklozenge ✦
imap <buffer> \sho ϸ
imap <buffer> \construction 🚧
imap <buffer> \sim ∼
imap <buffer> \ordmasculine º
imap <buffer> \sq. ▣
imap <buffer> \risingdotseq ≓
imap <buffer> \sqo ▢
imap <buffer> \textcircledP ℗
imap <buffer> \st6 ✶
imap <buffer> \textdiscount ⁒
imap <buffer> \st8 ✴
imap <buffer> \triangledown ▿
imap <buffer> \sub ⊂
imap <buffer> \triangleleft ◃
imap <buffer> \sum ∑
imap <buffer> \Longleftarrow ⇐
imap <buffer> \sup ⊃
imap <buffer> \^\c with curl ᶝ
imap <buffer> \tau τ
imap <buffer> \^\greek gamma ᵞ
imap <buffer> \tie ⁀
imap <buffer> \^\h with hook ʱ
imap <buffer> \top ⊤
imap <buffer> \^\ligature oe ꟹ
imap <buffer> \u-2 ⇈
imap <buffer> \^\m with hook ᶬ
imap <buffer> \u-<bar> ↥
imap <buffer> \^\s with hook ᶳ
imap <buffer> \u== ⟰
imap <buffer> \^\v with hook ᶹ
imap <buffer> \ud- ↕
imap <buffer> \^\z with curl ᶽ
imap <buffer> \ud= ⇕
imap <buffer> \bigtriangleup △
imap <buffer> \ul- ↖
imap <buffer> \blacktriangle ▴
imap <buffer> \ul= ⇖
imap <buffer> \divideontimes ⋇
imap <buffer> \ur- ↗
imap <buffer> \fallingdotseq ≒
imap <buffer> \ur= ⇗
imap <buffer> \hookleftarrow ↩
imap <buffer> \uu- ↟
imap <buffer> \leftarrowtail ↢
imap <buffer> \u{} ˘
imap <buffer> \leftharpoonup ↼
imap <buffer> \vee ∨
imap <buffer> \longleftarrow ←
imap <buffer> \v{} ˇ
imap <buffer> \looparrowleft ↫
imap <buffer> \won ₩
imap <buffer> \measuredangle ∡
imap <buffer> \yen ¥
imap <buffer> \ntriangleleft ⋪
imap <buffer> \<bar>-n ⊬
imap <buffer> \shortparallel ∥
imap <buffer> \<bar>=n ⊭
imap <buffer> \smallsetminus ∖
imap <buffer> \<bar><bar>- ⊩
imap <buffer> \textbigcircle ⃝
imap <buffer> \<bar><bar>= ⊫
imap <buffer> \textestimated ℮
imap <buffer> \<bar><bar>n ∦
imap <buffer> \triangleright ▹
imap <buffer> \~-n ≄
imap <buffer> \upleftharpoon ↿
imap <buffer> \~=n ≇
imap <buffer> \Leftrightarrow ⇔
imap <buffer> \~{} ˜
imap <buffer> \Longrightarrow ⇒
imap <buffer> \~~- ≊
imap <buffer> \^\turned alpha ᶛ
imap <buffer> \~~n ≉
imap <buffer> \curvearrowleft ↶
imap <buffer> \~~~ ≋
imap <buffer> \downdownarrows ⇊
imap <buffer> \"\'I Ḯ
imap <buffer> \hookrightarrow ↪
imap <buffer> \"\'U Ǘ
imap <buffer> \leftleftarrows ⇇
imap <buffer> \"\'i ḯ
imap <buffer> \leftrightarrow ↔
imap <buffer> \"\'u ǘ
imap <buffer> \leftthreetimes ⋋
imap <buffer> \"\=A Ǟ
imap <buffer> \longrightarrow →
imap <buffer> \"\=O Ȫ
imap <buffer> \looparrowright ↬
imap <buffer> \"\=U Ǖ
imap <buffer> \multiplication ×
imap <buffer> \"\=a ǟ
imap <buffer> \nshortparallel ∦
imap <buffer> \"\=o ȫ
imap <buffer> \ntriangleright ⋫
imap <buffer> \"\=u ǖ
imap <buffer> \rightarrowtail ↣
imap <buffer> \"\`U Ǜ
imap <buffer> \rightharpoonup ⇀
imap <buffer> \"\`u ǜ
imap <buffer> \sphericalangle ∢
imap <buffer> \"\vU Ǚ
imap <buffer> \textopenbullet ◦
imap <buffer> \"\vu ǚ
imap <buffer> \trianglelefteq ⊴
imap <buffer> \"{A} Ä
imap <buffer> \uprightharpoon ↾
imap <buffer> \"{E} Ë
imap <buffer> \^\H With Stroke ꟸ
imap <buffer> \"{H} Ḧ
imap <buffer> \^\bottom half o ᵕ
imap <buffer> \"{I} Ï
imap <buffer> \^\i with stroke ᶤ
imap <buffer> \"{O} Ö
imap <buffer> \^\turned open e ᵌ
imap <buffer> \"{U} Ü
imap <buffer> \^\turned r hook ʵ
imap <buffer> \"{W} Ẅ
imap <buffer> \bigtriangledown ▽
imap <buffer> \"{X} Ẍ
imap <buffer> \circlearrowleft ↺
imap <buffer> \"{Y} Ÿ
imap <buffer> \curvearrowright ↷
imap <buffer> \"{a} ä
imap <buffer> \downleftharpoon ⇃
imap <buffer> \"{e} ë
imap <buffer> \leftharpoondown ↽
imap <buffer> \"{h} ḧ
imap <buffer> \leftrightarrows ⇆
imap <buffer> \"{i} ï
imap <buffer> \nLeftrightarrow ⇎
imap <buffer> \"{o} ö
imap <buffer> \nleftrightarrow ↮
imap <buffer> \"{t} ẗ
imap <buffer> \ntrianglelefteq ⋬
imap <buffer> \"{u} ü
imap <buffer> \rightleftarrows ⇄
imap <buffer> \"{w} ẅ
imap <buffer> \rightthreetimes ⋌
imap <buffer> \"{x} ẍ
imap <buffer> \squigarrowright ⇝
imap <buffer> \"{y} ÿ
imap <buffer> \textinterrobang ‽
imap <buffer> \'\.S Ṥ
imap <buffer> \textmusicalnote ♪
imap <buffer> \'\.s ṥ
imap <buffer> \trianglerighteq ⊵
imap <buffer> \'\AE Ǽ
imap <buffer> \vartriangleleft ⊲
imap <buffer> \'\ae ǽ
imap <buffer> \circlearrowright ↻
imap <buffer> \'{A} Á
imap <buffer> \downrightharpoon ⇂
imap <buffer> \'{C} Ć
imap <buffer> \ntrianglerighteq ⋭
imap <buffer> \'{E} É
imap <buffer> \rightharpoondown ⇁
imap <buffer> \'{G} Ǵ
imap <buffer> \rightrightarrows ⇉
imap <buffer> \'{I} Í
imap <buffer> \twoheadleftarrow ↞
imap <buffer> \'{K} Ḱ
imap <buffer> \vartriangleright ⊳
imap <buffer> \'{L} Ĺ
imap <buffer> \^\reversed open e ᶟ
imap <buffer> \'{M} Ḿ
imap <buffer> \blacktriangledown ▾
imap <buffer> \'{N} Ń
imap <buffer> \blacktriangleleft ◂
imap <buffer> \'{O} Ó
imap <buffer> \leftrightharpoons ⇋
imap <buffer> \'{P} Ṕ
imap <buffer> \rightleftharpoons ⇌
imap <buffer> \'{R} Ŕ
imap <buffer> \textcolonmonetary ₡
imap <buffer> \'{S} Ś
imap <buffer> \textreferencemark ※
imap <buffer> \'{U} Ú
imap <buffer> \twoheadrightarrow ↠
imap <buffer> \'{W} Ẃ
imap <buffer> \Longleftrightarrow ⇔
imap <buffer> \'{Y} Ý
imap <buffer> \^\n with left hook ᶮ
imap <buffer> \'{Z} Ź
imap <buffer> \blacktriangleright ▸
imap <buffer> \'{a} á
imap <buffer> \longleftrightarrow ↔
imap <buffer> \'{c} ć
imap <buffer> \textpertenthousand ‱
imap <buffer> \'{e} é
imap <buffer> \leftrightsquigarrow ↭
imap <buffer> \'{g} ǵ
imap <buffer> \textfractionsolidus ⁄
imap <buffer> \'{i} í
imap <buffer> \^\capital inverted r ʶ
imap <buffer> \'{k} ḱ
imap <buffer> \^\turned r with hook ʵ
imap <buffer> \'{l} ĺ
imap <buffer> \^\j with crossed-tail ᶨ
imap <buffer> \'{m} ḿ
imap <buffer> \^\l with palatal hook ᶪ
imap <buffer> \'{n} ń
imap <buffer> \^\t with palatal hook ᶵ
imap <buffer> \'{o} ó
imap <buffer> \^\capital i with stroke ᶧ
imap <buffer> \'{p} ṕ
imap <buffer> \^\dotless j with stroke ᶡ
imap <buffer> \'{r} ŕ
imap <buffer> \^\l with retroflex hook ᶩ
imap <buffer> \'{s} ś
imap <buffer> \^\n with retroflex hook ᶯ
imap <buffer> \'{u} ú
imap <buffer> \^\reversed glottal stop ˤ
imap <buffer> \'{w} ẃ
imap <buffer> \^\z with retroflex hook ᶼ
imap <buffer> \'{y} ý
imap <buffer> \^\turned m with long leg ᶭ
imap <buffer> \' ′
imap <buffer> \( (
imap <buffer> \) )
imap <buffer> \. ∙
imap <buffer> \: ∶
imap <buffer> \T ◀
imap <buffer> \` ‵
imap <buffer> \b ♭
imap <buffer> \c ⌜
imap <buffer> \d ↓
imap <buffer> \i ∩
imap <buffer> \l ←
imap <buffer> \o ∘
imap <buffer> \r →
imap <buffer> \t ◂
imap <buffer> \u ↑
imap <buffer> \~ ∼
imap <buffer> \8< ✂
imap <buffer> \=o ≗
imap <buffer> \?! ‽
imap <buffer> \Tb ◀
imap <buffer> \Tw ◁
imap <buffer> \^. ̇
imap <buffer> \^A ᴬ
imap <buffer> \^E ᴱ
imap <buffer> \^G ᴳ
imap <buffer> \^H ᴴ
imap <buffer> \^I ᴵ
imap <buffer> \^J ᴶ
imap <buffer> \^O ᴼ
imap <buffer> \^U ᵁ
imap <buffer> \^W ᵂ
imap <buffer> \^^ ̂
imap <buffer> \^a ᵃ
imap <buffer> \^c ᶜ
imap <buffer> \^e ᵉ
imap <buffer> \^g ᵍ
imap <buffer> \^h ʰ
imap <buffer> \^i ⁱ
imap <buffer> \^j ʲ
imap <buffer> \^l ⃖
imap <buffer> \^o ᵒ
imap <buffer> \^r ⃗
imap <buffer> \^s ˢ
imap <buffer> \^u ᵘ
imap <buffer> \^v ̌
imap <buffer> \^w ʷ
imap <buffer> \^y ʸ
imap <buffer> \^z ᶻ
imap <buffer> \^~ ̃
imap <buffer> \_. ̣
imap <buffer> \_^ ̭
imap <buffer> \_v ̬
imap <buffer> \bu •
imap <buffer> \ci ●
imap <buffer> \cl ⌞
imap <buffer> \cu ⌜
imap <buffer> \di ◆
imap <buffer> \dl ↙
imap <buffer> \dr ↘
imap <buffer> \eq =
imap <buffer> \lr ↔
imap <buffer> \l~ ↜
imap <buffer> \pa ▰
imap <buffer> \re ▬
imap <buffer> \r~ ↝
imap <buffer> \sq ■
imap <buffer> \st ⋆
imap <buffer> \tb ◂
imap <buffer> \tw ◃
imap <buffer> \ud ↕
imap <buffer> \ul ↖
imap <buffer> \ur ↗
imap <buffer> \~n ≁
imap <buffer> \(1) ⑴
imap <buffer> \(2) ⑵
imap <buffer> \(3) ⑶
imap <buffer> \(4) ⑷
imap <buffer> \(5) ⑸
imap <buffer> \(6) ⑹
imap <buffer> \(7) ⑺
imap <buffer> \(8) ⑻
imap <buffer> \(9) ⑼
imap <buffer> \(a) ⒜
imap <buffer> \(b) ⒝
imap <buffer> \(c) ⒞
imap <buffer> \(d) ⒟
imap <buffer> \(e) ⒠
imap <buffer> \(f) ⒡
imap <buffer> \(g) ⒢
imap <buffer> \(h) ⒣
imap <buffer> \(i) ⒤
imap <buffer> \(j) ⒥
imap <buffer> \(k) ⒦
imap <buffer> \(l) ⒧
imap <buffer> \(m) ⒨
imap <buffer> \(n) ⒩
imap <buffer> \(o) ⒪
imap <buffer> \(p) ⒫
imap <buffer> \(q) ⒬
imap <buffer> \(r) ⒭
imap <buffer> \(s) ⒮
imap <buffer> \(t) ⒯
imap <buffer> \(u) ⒰
imap <buffer> \(v) ⒱
imap <buffer> \(w) ⒲
imap <buffer> \(x) ⒳
imap <buffer> \(y) ⒴
imap <buffer> \(z) ⒵
imap <buffer> \--- ─
imap <buffer> \--. ╌
imap <buffer> \--= ═
imap <buffer> \--_ ━
imap <buffer> \... ⋯
imap <buffer> \^-- ̅
imap <buffer> \_-- ̲
imap <buffer> \apl ⌶
imap <buffer> \die ⚀
imap <buffer> \eqn ≠
imap <buffer> \geq >
imap <buffer> \leq <
imap <buffer> \reb ▬
imap <buffer> \rew ▭
imap <buffer> \sqb ■
imap <buffer> \sqw □
imap <buffer> \st4 ✦
imap <buffer> \(10) ⑽
imap <buffer> \(11) ⑾
imap <buffer> \(12) ⑿
imap <buffer> \(13) ⒀
imap <buffer> \(14) ⒁
imap <buffer> \(15) ⒂
imap <buffer> \(16) ⒃
imap <buffer> \(17) ⒄
imap <buffer> \(18) ⒅
imap <buffer> \(19) ⒆
imap <buffer> \(20) ⒇
imap <buffer> \frac ¼
imap <buffer> \geqn ≯
imap <buffer> \join ⋈
imap <buffer> \leqn ≮
imap <buffer> \note ♩
imap <buffer> \angle ∟
imap <buffer> \union ∪
imap <buffer> \member ∈
imap <buffer> \entails ⊢
imap <buffer> \asterisk ⁎
imap <buffer> \integral ∫
imap <buffer> \intersection ∩
