if [[ -f $HOME/.rcfiles/zsh/zshrc.prompt ]]
then
    source $HOME/.rcfiles/zsh/zshrc.prompt
fi

if [[ -f $HOME/.rcfiles/zsh/zshrc.aliases ]]
then
    source $HOME/.rcfiles/zsh/zshrc.aliases
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

##########################
# Bindkey
##########################
bindkey -e
bindkey "\e[A"      history-beginning-search-backward
bindkey "\e[B"      history-beginning-search-forward
bindkey "\e[H"      beginning-of-line
bindkey "\e[F"      end-of-line
bindkey "\ej"       backward-word
bindkey "\ek"       forward-word

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/cychih/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
