#!/usr/bin/env bash

#Let "ls has pretty color
# a     black
# b     red
# c     green
# d     brown
# e     blue
# f     magenta
# g     cyan
# h     light grey
# x     default color

# 1.   directory
# 2.   symbolic link
# 3.   socket
# 4.   pipe
# 5.   executable
# 6.   block special
# 7.   character special
# 8.   executable with setuid bit set
# 9.   executable with setgid bit set
# 10.  directory writable to others, with sticky bit
# 11.  directory writable to others, without sticky bit
#                1 2 3 4 5 6 7 8 9 1011
export LSCOLORS="GxFxcxDxCxegedabagacad"

# di: directories
# ln: symbolic links
# pi: Named pipe
# ex: Executable file
export LS_COLORS='di=1;36:ln=1;35:pi=1;33:ex=1;32'

# See https://github.com/eza-community/eza/blob/main/man/eza_colors.5.md
# ur/uw/ux/ue: User rwx bit
# gr/gw/gx: Group rwx bit
# tr/tw/tx: Others rwx bit
# xa: Extended attribute marker
# sn/sb: Size number/unit
# uu: A user that’s you
# un: A user that’s not you
# da: Timestamp
# im: a regular file that is an image
# vi: a regular file that is a video
# mu: a regular file that is lossy music
# lo: a regular file that is lossless music
# sc: a regular file that is source code
export EZA_COLORS=\
'ur=0;32:uw=0;32:ux=0;32:ue=0;32:'\
'gr=0;32:gw=0;32:gx=0;32:'\
'tr=0;32:tw=0;32:tx=0;32:'\
'xa=0;32:'\
'sn=1;35:sb=0;35:'\
'uu=0;33:un=0;37:'\
'da=1;34:'\
'di=1;38;5;14:'\
'pi=1;38;5;11:'\
'im=38;5;135:'\
'vi=38;5;135:'\
'mu=38;5;135:'\
'lo=38;5;135:'\
'sc=0:'
EZA_COLORS="${EZA_COLORS%:}" # trim trailing ':'


export EDITOR=vim
export PAGER=less
export LESS='-R --mouse'
