#!/usr/bin/env bash


#Let "ls has pretty color
# a     black
# b     red
# c     green
# d     brown
# e     blue
# f     magenta
# g     cyan
# h     light grey
# x     default color

# 1.   directory
# 2.   symbolic link
# 3.   socket
# 4.   pipe
# 5.   executable
# 6.   block special
# 7.   character special
# 8.   executable with setuid bit set
# 9.   executable with setgid bit set
# 10.  directory writable to others, with sticky bit
# 11.  directory writable to others, without sticky bit
#                1 2 3 4 5 6 7 8 9 1011
export LSCOLORS="GxFxcxDxCxegedabagacad"
export LS_COLORS="di=01;36:ln=01;35"
